import { Data, IProductInput } from '@/types'
import { toSlug } from './utils'

//cat: 'chairs','sofas','tables','dining sets','beds'

const products: IProductInput[] = [


  {
    name: 'Modern Accent Chair',
    slug: toSlug('Modern Accent Chair'),
    category: 'chairs',
    images: ['/images/chair-1.jpg', '/images/chair-2.jpg'],
    tags: ['latest', 'best-seller'],
    isPublished: true,
    price: 13000,
    listPrice: 0,
    brand: 'Urban Living',
    avgRating: 4.8,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 4 },
      { rating: 5, count: 10 },
    ],
    numSales: 30,
    countInStock: 25,
    description: 'A stylish accent chair designed for comfort and elegance.',
    sizes: ['One Size'],
    colors: ['Grey', 'Blue', 'Black'],
    reviews: [],
  },
  {
    name: 'Contemporary Armchair',
    slug: toSlug('Contemporary Armchair'),
    category: 'chairs',
    images: ['/images/chair-3.jpg'],
    tags: ['latest'],
    isPublished: true,
    price: 11000,
    listPrice: 0,
    brand: 'ComfortChoice',
    avgRating: 4.7,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 5 },
      { rating: 5, count: 3 },
    ],
    numSales: 20,
    countInStock: 15,
    description: 'A modern armchair that adds a touch of class to your home.',
    sizes: ['One Size'],
    colors: ['Green', 'Beige'],
    reviews: [],
  },
  {
    name: 'Classic Dining Chair',
    slug: toSlug('Classic Dining Chair'),
    category: 'chairs',
    images: [ '/images/chair-4.jpg'],
    tags: ['best-seller'],
    isPublished: true,
    price: 22000,
    listPrice: 0,
    brand: 'Timeless Comfort',
    avgRating: 4.5,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 3 },
      { rating: 4, count: 8 },
      { rating: 5, count: 6 },
    ],
    numSales: 35,
    countInStock: 30,
    description: 'Simple and elegant dining chair that suits any table.',
    sizes: ['One Size'],
    colors: ['White', 'Wood'],
    reviews: [],
  },
  {
    name: 'Luxury Leather Sofa',
    slug: toSlug('Luxury Leather Sofa'),
    category: 'sofas',
    images: ['/images/sofa-1.jpg', '/images/sofa-2.jpg'],
    tags: ['latest'],
    isPublished: true,
    price: 71000,
    listPrice: 0,
    brand: 'ComfortPlus',
    avgRating: 4.9,
    numReviews: 20,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 3 },
      { rating: 5, count: 17 },
    ],
    numSales: 50,
    countInStock: 15,
    description: 'Premium leather sofa providing ultimate comfort and luxury.',
    sizes: ['2-Seater', '3-Seater'],
    colors: ['Black', 'Brown'],
    reviews: [],
  },
  {
    name: 'Modern Fabric Sofa',
    slug: toSlug('Modern Fabric Sofa'),
    category: 'sofas',
    images: ['/images/sofa-3.jpg', '/images/sofa-4.jpg'],
    tags: ['latest', 'best-seller'],
    isPublished: true,
    price: 66000,
    listPrice: 0,
    brand: 'Urban Comfort',
    avgRating: 4.6,
    numReviews: 18,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 3 },
      { rating: 4, count: 6 },
      { rating: 5, count: 8 },
    ],
    numSales: 40,
    countInStock: 20,
    description: 'A comfortable fabric sofa designed for modern living rooms.',
    sizes: ['3-Seater'],
    colors: ['Grey', 'Navy Blue'],
    reviews: [],
  },
  {
    name: 'Wooden Coffee Table',
    slug: toSlug('Wooden Coffee Table'),
    category: 'tables',
    images: ['/images/table-1.jpg', '/images/tab1e-2.jpg'],
    tags: ['latest'],
    isPublished: true,
    price: 18000,
    listPrice: 0,
    brand: 'HomeStyle',
    avgRating: 4.6,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 6 },
      { rating: 5, count: 4 },
    ],
    numSales: 40,
    countInStock: 20,
    description: 'Durable wooden coffee table with a sleek modern design.',
    sizes: ['One Size'],
    colors: ['Natural Wood', 'Dark Oak'],
    reviews: [],
  },
  {
    name: 'Glass Dining Table',
    slug: toSlug('Glass Dining Table'),
    category: 'tables',
    images: ['/images/table-3.jpg', '/images/table-4.jpg'],
    tags: ['latest', 'best-seller'],
    isPublished: true,
    price: 22000,
    listPrice: 0,
    brand: 'Contemporary Designs',
    avgRating: 4.8,
    numReviews: 22,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 10 },
      { rating: 5, count: 9 },
    ],
    numSales: 45,
    countInStock: 18,
    description: 'A sleek and modern glass dining table perfect for contemporary homes.',
    sizes: ['One Size'],
    colors: ['Clear', 'Black'],
    reviews: [],
  },
  {
    name: '6-Piece Dining Set',
    slug: toSlug('6-Piece Dining Set'),
    category: 'dining sets',
    images: ['/images/dining-1.jpg', '/images/dining-2.jpg'],
    tags: ['latest'],
    isPublished: true,
    price: 29000,
    listPrice: 0,
    brand: 'Elegance Furnishings',
    avgRating: 4.7,
    numReviews: 18,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 3 },
      { rating: 4, count: 8 },
      { rating: 5, count: 7 },
    ],
    numSales: 35,
    countInStock: 10,
    description: 'Elegant 6-piece dining set with comfortable chairs and a spacious table.',
    sizes: ['One Size'],
    colors: ['White', 'Walnut'],
    reviews: [],
  },
  {
    name: '4-Piece Dining Set',
    slug: toSlug('4-Piece Dining Set'),
    category: 'dining sets',
    images: ['/images/dining-3.jpg', '/images/dining-4.jpg'],
    tags: ['best-seller'],
    isPublished: true,
    price: 27000,
    listPrice: 0,
    brand: 'Modern Living',
    avgRating: 4.5,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 4 },
      { rating: 4, count: 5 },
      { rating: 5, count: 5 },
    ],
    numSales: 28,
    countInStock: 12,
    description: 'Compact and stylish 4-piece dining set for small spaces.',
    sizes: ['One Size'],
    colors: ['Black', 'Oak'],
    reviews: [],
  },
  {
    name: 'King Size Bed with Storage',
    slug: toSlug('King Size Bed with Storage'),
    category: 'beds',
    images: ['/images/bed-1.jpg', '/images/bed-2.jpg'],
    tags: ['best-seller'],
    isPublished: true,
    price: 52000,
    listPrice: 0,
    brand: 'DreamHome',
    avgRating: 4.85,
    numReviews: 25,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 4 },
      { rating: 5, count: 20 },
    ],
    numSales: 60,
    countInStock: 12,
    description: 'Spacious king size bed with built-in storage for a tidy bedroom.',
    sizes: ['King Size'],
    colors: ['Grey', 'Black'],
    reviews: [],
  },
  {
    name: 'Queen Size Bed',
    slug: toSlug('Queen Size Bed'),
    category: 'beds',
    images: ['/images/bed-3.jpg', '/images/bed-4.jpg'],
    tags: ['latest'],
    isPublished: true,
    price: 48000,
    listPrice: 0,
    brand: 'CozySleep',
    avgRating: 4.7,
    numReviews: 30,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 4 },
      { rating: 4, count: 10 },
      { rating: 5, count: 15 },
    ],
    numSales: 70,
    countInStock: 20,
    description: 'Comfortable queen size bed designed for maximum relaxation.',
    sizes: ['Queen Size'],
    colors: ['Light Beige', 'Charcoal'],
    reviews: [],
  }
  
]



const data: Data = {
    headerMenus: [
      // {
      //   name: "Today's Deal",
      //   href: '/search?tag=todays-deal',
      // },
      {
        name: 'Latest Products',
        href: '/search?tag=latest',
      },
      // {
      //   name: 'Featured Products',
      //   href: '/search?tag=featured',
      // },
      {
        name: 'Best Sellers',
        href: '/search?tag=best-seller',
      },
    //   {
    //     name: 'Browsing History',
    //     href: '/#browsing-history',
    //   },
    //   {
    //     name: 'Customer Service',
    //     href: '/page/customer-service',
    //   },
    //   {
    //     name: 'About Us',
    //     href: '/page/about-us',
    //   },
    //   {
    //     name: 'Help',
    //     href: '/page/help',
    //   },
    ],
    products,
  }
  
  export default data